version: '3.8'
services:
  copymanga-web:
    image: ghcr.io/mogvl/copymanga-web:latest

    container_name: copymanga-web
    ports:
      - "3000:8080"
    environment:
      # 下载目录（容器内路径）
      - DOWNLOAD_DIR=/downloads
      - STATIC_DIR=/app/static
      - PORT=8080
    volumes:
      # !!! 重要: 把 /volume1/漫画 改成你存漫画的路径 !!!
      - /volume1/漫画:/downloads
    restart: unless-stopped
